### ISSUE TITLE
KRB5CCNAME=DIR makes kinit crash

### ISSUE THREAD

**Issue by riastradh** [heimdal/heimdal#1108]
**Describe the bug**
```
% KRB5CCNAME=DIR ./prefix/bin/kinit nobody@EXAMPLE.COM
zsh: segmentation fault (core dumped)  KRB5CCNAME=DIR ./prefix/bin/kinit
% gdb ./prefix/bin/kinit ./kinit.core
GNU gdb (GDB) 8.3
...
Program terminated with signal SIGSEGV, Segmentation fault.
#0  dcc_resolve_2 (context=0x7d34bd235000, id=0x7f7fff7245c8, res=0x0, sub=0x0)
    at ../../../../master/lib/krb5/dcache.c:380
380             if (*res == '\0' || (res[0] == ':' && res[1] == '\0')) {
(gdb) bt
#0  dcc_resolve_2 (context=0x7d34bd235000, id=0x7f7fff7245c8, res=0x0, sub=0x0)
    at ../../../../master/lib/krb5/dcache.c:380
#1  0x00007d34bcc2b682 in allocate_ccache (
    context=context@entry=0x7d34bd235000, ops=0x7d34bce942e0 <krb5_dcc_ops>,
    residual=<optimized out>, subsidiary=subsidiary@entry=0x0,
    id=0x7f7fff7245c8) at ../../../../master/lib/krb5/cache.c:212
#2  0x00007d34bcc2b6be in krb5_cc_resolve (context=0x7d34bd235000,
    name=<optimized out>, id=id@entry=0x7f7fff7245c8)
    at ../../../../master/lib/krb5/cache.c:253
#3  0x00007d34bcc2c2a6 in krb5_cc_default (context=<optimized out>,
    id=id@entry=0x7f7fff7245c8) at ../../../../master/lib/krb5/cache.c:853
#4  0x0000000000407d9e in main (argc=1, argv=0x7f7fff724a70)
    at ../../../master/kuser/kinit.c:1793
(gdb) fr 1
#1  0x00007d34bcc2b682 in allocate_ccache (
    context=context@entry=0x7d34bd235000, ops=0x7d34bce942e0 <krb5_dcc_ops>,
    residual=<optimized out>, subsidiary=subsidiary@entry=0x0,
    id=0x7f7fff7245c8) at ../../../../master/lib/krb5/cache.c:212
212                 ret = (*id)->ops->resolve_2(context, id, exp_residual, subsidiary);
(gdb) info locals
ret = 0
exp_residual = 0x0
filepath = <optimized out>
```

**To Reproduce**
```
KRB5CCNAME=DIR kinit nobody@EXAMPLE.COM
```

built from commit 442664d94f532a6286e3e844c9196416f4d17257 (plus some minor local changes to fix build errors)

**Expected behavior**
not SIGSEGV

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: NetBSD
 - Browser: N/A
 - Version: 9

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by nicowilliams** [comment]
Which branch is this in?

**Comment by nicowilliams** [comment]
Thanks!  Should be an easy fix.
