### ISSUE TITLE
X509 card-based logins fail with SIGSEGV

### ISSUE THREAD

**Issue by madscientist159** [heimdal/heimdal#202]
Heimdal's X509 PAM authentication plugin crashes with the following backtrace when attempting to use a cryptographic card to log in.

Heimdal version: Debian 1.7~git20160703+dfsg-1 (Debian Stretch)

```
Program received signal SIGSEGV, Segmentation fault.
0x00007f5c0f30e38d in _hx509_match_keys (c=0x18e2ed0, key=0x18e0960) at crypto.c:3018
3018    crypto.c: No such file or directory.
(gdb) bt
#0  0x00007f5c0f30e38d in _hx509_match_keys (c=0x18e2ed0, key=0x18e0960) at crypto.c:3018
#1  0x00007f5c0f30b17b in match_keys (value=0x18e0500, certs=0x18e1620, context=0x18a0430) at collector.c:232
#2  _hx509_collector_collect_certs (context=context@entry=0x18a0430, c=0x18e0b30, ret_certs=ret_certs@entry=0x18e0438) at collector.c:275
#3  0x00007f5c0f315669 in p11_list_keys (certs=0x18e0438, lock=<optimized out>, session=26085952, slot=0x18e0410, p=0x18a3740, context=0x18a0430) at ks_p11.c:804
#4  p11_init_slot (context=context@entry=0x18a0430, p=p@entry=0x18a3740, lock=lock@entry=0x18a36a0, id=<optimized out>, num=<optimized out>, slot=0x18e0410) at ks_p11.c:363
#5  0x00007f5c0f315963 in p11_init (context=0x18a0430, certs=<optimized out>, data=0x1889f70, flags=<optimized out>, residue=<optimized out>, lock=0x18a36a0) at ks_p11.c:933
#6  0x00007f5c0f311b10 in hx509_certs_init (context=0x18a0430, name=name@entry=0x1867910 "PKCS11:/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so", flags=flags@entry=0, lock=0x18a36a0, certs=certs@entry=0x18a3668) at keyset.c:159
#7  0x00007f5c0fc72f0f in _krb5_pk_load_id (context=context@entry=0x18a0240, ret_id=0x18a3580, user_id=user_id@entry=0x1867910 "PKCS11:/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so",
    anchor_id=anchor_id@entry=0x18a3440 "FILE:/<redacted>", chain_list=0x0, revoke_list=0x1889ba0, prompter=0x7f5c0feb30d0, prompter_data=0x1867740, password=0x0) at pkinit.c:1882
#8  0x00007f5c0fc74b07 in krb5_get_init_creds_opt_set_pkinit (context=0x18a0240, opt=0x1867810, principal=0x1867880, user_id=0x1867910 "PKCS11:/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so",
    x509_anchors=0x18a3440 "FILE:<redacted>", pool=<optimized out>, pki_revoke=<optimized out>, flags=0, prompter=0x7f5c0feb30d0, prompter_data=0x1867740, password=0x0) at pkinit.c:2394
#9  0x00007f5c0feb0e49 in ?? () from /lib/x86_64-linux-gnu/security/pam_krb5.so
#10 0x00007f5c0feb175b in ?? () from /lib/x86_64-linux-gnu/security/pam_krb5.so
#11 0x00007f5c0feb36b7 in pam_sm_authenticate () from /lib/x86_64-linux-gnu/security/pam_krb5.so
#12 0x00007f5c123c80a6 in ?? () from /lib/x86_64-linux-gnu/libpam.so.0
#13 0x00007f5c123c781d in pam_authenticate () from /lib/x86_64-linux-gnu/libpam.so.0
#14 0x00000000004031b3 in ?? ()
#15 0x00007f5c11c18700 in __libc_start_main (main=0x402a90, argc=3, argv=0x7ffd37fe93f8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd37fe93e8) at ../csu/libc-start.c:291
#16 0x0000000000404200 in ?? ()
```

**Comment by madscientist159** [comment]
Also for reference, the identical configuration worked with Heimdal 1.6 (Debian Jessie).

**Comment by madscientist159** [comment]
This turned out to be a mistake; we were compiling newer versions of Heimdal for Jessie but not for Stretch.  Closing.
